Day-Walk/BackEnd

build.gradle, src/main/java/com/day_walk/backend/BackendApplication.java, src/main/java/com/day_walk/backend/domain/category/bean/GetCategoryEntityBean.java, src/main/java/com/day_walk/backend/domain/category/controller/CategoryController.java, src/main/java/com/day_walk/backend/domain/category/data/CategoryEntity.java, src/main/java/com/day_walk/backend/domain/category/data/dto/out/GetCategoryDto.java, src/main/java/com/day_walk/backend/domain/category/repository/CategoryRepository.java, src/main/java/com/day_walk/backend/domain/category/service/CategoryService.java, src/main/java/com/day_walk/backend/domain/tag/bean/GetTagBean.java, src/main/java/com/day_walk/backend/domain/tag/controller/TagController.java, src/main/java/com/day_walk/backend/domain/tag/data/TagEntity.java, src/main/java/com/day_walk/backend/domain/tag/data/out/GetTagByCategoryDto.java, src/main/java/com/day_walk/backend/domain/tag/data/out/GetTagByPlaceDto.java, src/main/java/com/day_walk/backend/domain/tag/repository/TagRepository.java, src/main/java/com/day_walk/backend/domain/tag/service/TagService.java, src/main/java/com/day_walk/backend/global/BaseEntity.java, src/main/java/com/day_walk/backend/global/config/WebSecurityConfig.java
> #2 
> 카테고리와 태그 관련 기능 구현
> BaseEntity와 WebSecurityConfig 설정
=> feat: 카테고리와 태그 관련 기능

src/main/java/com/day_walk/backend/global/error/CustomException.java, src/main/java/com/day_walk/backend/global/error/ErrorCode.java, src/main/java/com/day_walk/backend/global/error/GlobalExceptionHandler.java, src/main/java/com/day_walk/backend/global/error/ResponseErrorEntity.java
> #17 
> Custom Error 관련 로직 구현
=> feat: error 관련 기능

src/main/java/com/day_walk/backend/domain/place/data/out/GetPlaceByLikeDto.java, src/main/java/com/day_walk/backend/domain/place_like/bean/DeletePlaceLikeEntityBean.java, src/main/java/com/day_walk/backend/domain/place_like/bean/GetPlaceLikeEntityBean.java, src/main/java/com/day_walk/backend/domain/place_like/bean/SavePlaceLikeEntityBean.java, src/main/java/com/day_walk/backend/domain/place_like/controller/PlaceLikeController.java, src/main/java/com/day_walk/backend/domain/place_like/data/PlaceLikeEntity.java, src/main/java/com/day_walk/backend/domain/place_like/data/in/DeletePlaceLikeDto.java, src/main/java/com/day_walk/backend/domain/place_like/data/in/SavePlaceLikeDto.java, src/main/java/com/day_walk/backend/domain/place_like/repository/PlaceLikeRepository.java, src/main/java/com/day_walk/backend/domain/place_like/service/PlaceLikeService.java
> #15 
> 장소 찜 추가, 삭제 API 구현
> 리뷰 merge 후 장소별 별점 추가 예정
=> feat: 장소 찜 관련 기능

src/main/java/com/day_walk/backend/domain/course/bean/GetCourseEntityBean.java, src/main/java/com/day_walk/backend/domain/course/bean/SaveCourseEntityBean.java, src/main/java/com/day_walk/backend/domain/course/controller/CourseController.java, src/main/java/com/day_walk/backend/domain/course/data/CourseEntity.java, src/main/java/com/day_walk/backend/domain/course/data/dto/in/ChangeBooleanDto.java, src/main/java/com/day_walk/backend/domain/course/data/dto/in/ModifyCourseTitleDto.java, src/main/java/com/day_walk/backend/domain/course/data/dto/in/SaveCourseDto.java, src/main/java/com/day_walk/backend/domain/course/data/dto/out/GetCourseDto.java, src/main/java/com/day_walk/backend/domain/course/repository/CourseRepository.java, src/main/java/com/day_walk/backend/domain/course/service/CourseService.java
> #12 
> 코스 저장 기능, 코스 이름 수정 기능, 코스 삭제 기능, 코스 공개 여부 변경 기능, 코스 상세 조회 기능 초기 구현
=> feat: 코스 관련 기능 구현

src/main/java/com/day_walk/backend/domain/course/bean/GetAllCourseEntityBean.java, src/main/java/com/day_walk/backend/domain/course/bean/GetSearchCourseEntityBean.java, src/main/java/com/day_walk/backend/domain/course/bean/GetUsersAllCourseEntityBean.java, src/main/java/com/day_walk/backend/domain/course/controller/CourseController.java, src/main/java/com/day_walk/backend/domain/course/data/CourseEntity.java, src/main/java/com/day_walk/backend/domain/course/data/dto/out/GetAllCourseDto.java, src/main/java/com/day_walk/backend/domain/course/data/dto/out/GetCourseDto.java, src/main/java/com/day_walk/backend/domain/course/data/dto/out/GetSearchCourseDto.java, src/main/java/com/day_walk/backend/domain/course/data/dto/out/GetUsersAllCourseDto.java, src/main/java/com/day_walk/backend/domain/course/repository/CourseRepository.java, src/main/java/com/day_walk/backend/domain/course/service/CourseService.java
> #21 
> 코스 검색 기능, 코스 상세 조회 기능,  코스 전체 조회 기능, 유저별 코스 전체 조회 기능
=> feat: 코스 조회 관련 기능

src/main/java/com/day_walk/backend/domain/course/bean/GetSearchCourseEntityBean.java, src/main/java/com/day_walk/backend/domain/course/bean/GetUsersAllCourseEntityBean.java, src/main/java/com/day_walk/backend/domain/course/controller/CourseController.java, src/main/java/com/day_walk/backend/domain/course/data/dto/out/GetAllCourseDto.java, src/main/java/com/day_walk/backend/domain/course/data/dto/out/GetCourseDto.java, src/main/java/com/day_walk/backend/domain/course/data/dto/out/GetSearchCourseDto.java, src/main/java/com/day_walk/backend/domain/course/data/dto/out/GetUsersAllCourseDto.java, src/main/java/com/day_walk/backend/domain/course/service/CourseService.java
> #27 
> 코스 상세 조회 ( like, courseLike, placeList 추가 )
> 코스 전체 조회 ( param에 userId 추가, placeList, like, courselike 추가 )
> 코스 검색 ( param에 userId 추가, placeList, like, courseLike 추가 )
> 유저별 코스 전체 조회 ( placeList 추가 )
=> feat: 코스 조회 관련 기능 추가 작업

src/main/java/com/day_walk/backend/domain/place/controller/PlaceController.java, src/main/java/com/day_walk/backend/domain/place/data/out/GetPlaceDto.java, src/main/java/com/day_walk/backend/domain/place/service/PlaceService.java, src/main/java/com/day_walk/backend/domain/place_like/bean/GetPlaceLikeEntityBean.java, src/main/java/com/day_walk/backend/domain/place_like/controller/PlaceLikeController.java, src/main/java/com/day_walk/backend/domain/place_like/repository/PlaceLikeRepository.java, src/main/java/com/day_walk/backend/domain/place_like/service/PlaceLikeService.java, src/main/java/com/day_walk/backend/domain/review/controller/ReviewController.java
> #37 
> 장소 상세 조회시 조회되지 않던 데이터 추가
리뷰 swagger api 명세서 오타 수정
=> feat: 장소 상세 조회 로직 수정

src/main/java/com/day_walk/backend/domain/user_like/bean/SaveUserLikeEntityBean.java, src/main/java/com/day_walk/backend/domain/user_like/data/UserLikeEntity.java, src/main/java/com/day_walk/backend/domain/user_like/data/dto/in/SaveCategoryListDto.java, src/main/java/com/day_walk/backend/domain/user_like/service/UserLikeService.java
=> refactor: 유저 선호 저장

src/main/java/com/day_walk/backend/BackendApplication.java, src/main/java/com/day_walk/backend/domain/course/controller/CourseController.java, src/main/java/com/day_walk/backend/domain/course/service/CourseService.java, src/main/java/com/day_walk/backend/domain/course_like/service/CourseLikeService.java, src/main/java/com/day_walk/backend/domain/place/controller/PlaceController.java, src/main/java/com/day_walk/backend/domain/place/data/out/GetPlaceBySearchDto.java, src/main/java/com/day_walk/backend/domain/place/data/out/GetPlaceDto.java, src/main/java/com/day_walk/backend/domain/place/service/PlaceService.java, src/main/java/com/day_walk/backend/domain/place_like/bean/GetPlaceLikeEntityBean.java, src/main/java/com/day_walk/backend/domain/place_like/controller/PlaceLikeController.java, src/main/java/com/day_walk/backend/domain/place_like/data/in/DeletePlaceLikeDto.java, src/main/java/com/day_walk/backend/domain/place_like/service/PlaceLikeService.java, src/main/java/com/day_walk/backend/domain/review/data/out/GetReviewByUserDto.java, src/main/java/com/day_walk/backend/domain/review/service/ReviewService.java, src/main/java/com/day_walk/backend/global/error/ErrorCode.java, src/main/resources/application.properties
> #47 
> 변수명 통일화
> place-like, course-like validation check 추가
> timezone 설정
=> feat: api 명세서 통일화

src/main/java/com/day_walk/backend/domain/user/bean/GetUserByKakaoIdBean.java, src/main/java/com/day_walk/backend/domain/user/controller/UserController.java, src/main/java/com/day_walk/backend/domain/user/data/UserEntity.java, src/main/java/com/day_walk/backend/domain/user/data/UserRole.java, src/main/java/com/day_walk/backend/domain/user/data/dto/in/SaveUserDto.java, src/main/java/com/day_walk/backend/domain/user/data/dto/in/SignInUserDto.java, src/main/java/com/day_walk/backend/domain/user/data/dto/out/GetUserBySignInDto.java, src/main/java/com/day_walk/backend/domain/user/repository/UserRepository.java, src/main/java/com/day_walk/backend/domain/user/service/UserService.java
> #49 
> 최초 로그인 유저의 회원가입 및 기존 유저의 로그인 기능 구현 완료
=> feat: 회원가입 및 로그인 기능 구현 완료

.gitignore, build.gradle, src/main/java/com/day_walk/backend/domain/user/controller/UserController.java, src/main/java/com/day_walk/backend/domain/user/service/UserService.java, src/main/java/com/day_walk/backend/global/config/WebSecurityConfig.java, src/main/java/com/day_walk/backend/global/token/JwtAuthenticationFilter.java, src/main/java/com/day_walk/backend/global/token/JwtUtil.java, src/main/resources/application.properties
=> feat: token 추가

src/main/java/com/day_walk/backend/domain/user/data/UserEntity.java, src/main/java/com/day_walk/backend/domain/user/service/UserService.java
> #49 
> 유저 초기정보 저장 안한상태로 로그인 시 nextPage = init으로 설정
=> refactor: 로그인 로직 수정

src/main/java/com/day_walk/backend/domain/category/controller/CategoryController.java, src/main/java/com/day_walk/backend/domain/image/controller/ImageController.java, src/main/java/com/day_walk/backend/domain/image/service/ImageService.java, src/main/java/com/day_walk/backend/domain/user/data/dto/out/GetUserBySignInDto.java, src/main/java/com/day_walk/backend/domain/user/service/UserService.java
=> feat: S3 이미지 업로드 API 기능 구현 완료

.gitignore, src/main/resources/application.properties
> #60 
> .gitignore, application.properties
=> feat: .gitignore, application.properties

src/main/java/com/day_walk/backend/domain/course/service/CourseService.java, src/main/java/com/day_walk/backend/domain/course_like/bean/GetCourseLikeEntityBean.java, src/main/java/com/day_walk/backend/domain/course_like/repository/CourseLikeRedisRepository.java, src/main/java/com/day_walk/backend/domain/place/bean/GetPlaceEntityBean.java, src/main/java/com/day_walk/backend/domain/place/controller/PlaceController.java, src/main/java/com/day_walk/backend/domain/place/repository/PlaceRepository.java, src/main/java/com/day_walk/backend/domain/place/service/PlaceService.java, src/main/java/com/day_walk/backend/domain/place_like/bean/GetPlaceLikeEntityBean.java, src/main/java/com/day_walk/backend/domain/place_like/repository/PlaceLikeRedisRepository.java
> #65 
> course-like와 course 연결
=> feat: course-like 와 course 연결

src/main/java/com/day_walk/backend/domain/course/controller/CourseController.java, src/main/java/com/day_walk/backend/domain/course/service/CourseService.java
=> feat: course 상세조회 로직 수정

src/main/java/com/day_walk/backend/domain/course/service/CourseService.java
> #68 
> 상세 조회시 이미지가 없을 경우 장소가 null로 반환되는 예외처리 수정
=> fix: 예외처리 수정

src/main/java/com/day_walk/backend/domain/place/data/out/GetPlaceByLikeDto.java, src/main/java/com/day_walk/backend/domain/place_like/repository/PlaceLikeRedisRepository.java, src/main/java/com/day_walk/backend/domain/place_like/service/PlaceLikeService.java
=> fix: null값 처리 추가

src/main/java/com/day_walk/backend/domain/place/data/out/GetPlaceBySearchDto.java, src/main/java/com/day_walk/backend/domain/place/service/PlaceService.java
=> feat: 장소 검색시 별점 추가

src/main/java/com/day_walk/backend/domain/image/service/ImageService.java
> #60 
> bucket에 prefix 추가 및 반영
=> refactor: prefix 추가

src/main/java/com/day_walk/backend/domain/review/data/out/GetReviewByUserDto.java
> #86
> GetReviewByUserDto에 placeId 추가
=> refactor: 유저별 리뷰 전체 조회에 plaeceId 추가

src/main/java/com/day_walk/backend/domain/course/service/CourseService.java
> #89 
> 코스 상세 조회시 코스를 생성한 유저일 경우 비활성화된 코스라도 상세조회 가능하도록 로직 변경
=> feat: 코스 상세 조회 로직 수정

src/main/java/com/day_walk/backend/domain/course/service/CourseService.java
=> feat: error 로직 수정

.gitignore, src/main/java/com/day_walk/backend/domain/place/data/in/GetPlaceByMlDto.java, src/main/java/com/day_walk/backend/domain/place/data/in/GetPlaceDetailByMlDto.java, src/main/java/com/day_walk/backend/domain/place/data/in/GetPlaceListByMlDto.java, src/main/java/com/day_walk/backend/domain/place/data/out/GetPlaceDto.java, src/main/java/com/day_walk/backend/domain/place/service/PlaceService.java, src/main/java/com/day_walk/backend/global/config/RestTemplateConfig.java, src/main/resources/application.properties
=> feat: search place add ml

src/main/java/com/day_walk/backend/domain/place/data/out/GetPlaceDto.java
> #100 
> 전화번호 자료형 String -> List로 변환
> 전화번호가 없을 경우 빈 배열 반환
=> fix: 자료형 변경

src/main/java/com/day_walk/backend/domain/chat/service/SseEmitters.java, src/main/java/com/day_walk/backend/global/config/SseClient.java
> #94 
> ChatBot 응답 전송 완료시 서버에서 Connection 종료 코드 추가
=> hotfix: 챗봇 응답 전송 완료시 커넥션 종료

src/main/java/com/day_walk/backend/domain/user_like/data/UserLikeEntity.java
> 
> user-like의 필드 중 tagList에 converter 추가
=> hotfix: tagList에 converter 추가

src/main/java/com/day_walk/backend/domain/course/data/CourseEntity.java, src/main/java/com/day_walk/backend/domain/place/data/PlaceEntity.java, src/main/java/com/day_walk/backend/domain/review/data/ReviewEntity.java, src/main/java/com/day_walk/backend/domain/user/controller/UserController.java, src/main/java/com/day_walk/backend/domain/user_like/data/UserLikeEntity.java, src/main/java/com/day_walk/backend/global/config/WebSecurityConfig.java, src/main/java/com/day_walk/backend/global/error/ErrorCode.java, src/main/java/com/day_walk/backend/global/token/GenerateCookie.java, src/main/java/com/day_walk/backend/global/token/JwtAuthenticationFilter.java, src/main/java/com/day_walk/backend/global/token/JwtUtil.java
> #107 
> header에 넣어주던 token을 cookie에 넣어서 반환
> access token, refresh token 생성
> cors 추가
=> refactor: token header to cookie

src/main/java/com/day_walk/backend/domain/chat/data/in/GetChatByMlDto.java, src/main/java/com/day_walk/backend/domain/chat/data/out/GetChatDto.java, src/main/java/com/day_walk/backend/domain/chat/service/SseEmitters.java, src/main/java/com/day_walk/backend/domain/place/data/out/GetPlaceByChatDto.java, src/main/java/com/day_walk/backend/global/config/SseClient.java
> hotfix
> chatbot의 요청과 응답 형태 변경
=> fix: chatbot request, response 변경

src/main/java/com/day_walk/backend/global/config/WebSecurityConfig.java
=> refactor: cors 설정 url 추가

src/main/java/com/day_walk/backend/domain/click_log/controller/ClickLogController.java, src/main/java/com/day_walk/backend/domain/click_log/data/dto/in/SaveClickLogDto.java, src/main/java/com/day_walk/backend/domain/click_log/service/ClickLogService.java
=> feat: click-log 저장 API 구현 완료

src/main/java/com/day_walk/backend/domain/click_log/controller/ClickLogController.java, src/main/java/com/day_walk/backend/domain/click_log/data/in/SaveClickLogDto.java, src/main/java/com/day_walk/backend/domain/click_log/data/out/SaveClickLogByElkDto.java, src/main/java/com/day_walk/backend/domain/click_log/service/ClickLogService.java, src/main/java/com/day_walk/backend/domain/course/bean/GetAllCourseEntityBean.java, src/main/java/com/day_walk/backend/domain/course/data/out/GetAllCourseDto.java, src/main/java/com/day_walk/backend/domain/course/service/CourseService.java, src/main/java/com/day_walk/backend/domain/review/service/ReviewService.java
> #126, #124, #123, #127
> 리뷰 NullPointerException Error Handling 추가
> 코스 조회시 정렬 기준 수정
> 코스 상세 조회시 코스 제작자명 반환되도록 수정
> click log 저장시 elk에 넘겨줄 timestamp를 프론트가 아닌 백엔드에서 처리하도록 수정
=> fix: 문제상황 수정

src/main/java/com/day_walk/backend/domain/user/controller/UserController.java, src/main/java/com/day_walk/backend/global/token/GenerateCookie.java, src/main/java/com/day_walk/backend/global/token/JwtAuthenticationFilter.java
> hotfix
> 로그아웃 기능 추가
> 사용자 권한 확인 기능 추가
=> feat: logout

src/main/java/com/day_walk/backend/domain/course/bean/GetSearchCourseEntityBean.java, src/main/java/com/day_walk/backend/domain/course/data/out/GetCourseDto.java, src/main/java/com/day_walk/backend/domain/course/data/out/GetSearchCourseDto.java, src/main/java/com/day_walk/backend/domain/course/data/out/GetUsersAllCourseDto.java, src/main/java/com/day_walk/backend/domain/course/repository/CourseRepository.java, src/main/java/com/day_walk/backend/domain/course/service/CourseService.java
> #144 
> 닉네임 기반 코스 검색 기능 추가, 코스 createAt 반환 추가
=> feat: 코스 검색 By userName 기능 추가 완료
